### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-200-fall-2023/circuit-scramble-assignment#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## ARMv6 Assembly

- [ ] equality&#x2F;program.S uses AND bitwise logic instruction
- [ ] equality&#x2F;program.S uses OR bitwise logic instruction
- [x] equality&#x2F;program.S uses NOT bitwise logic instruction
- [ ] equality&#x2F;program.S uses a comparison instruction
- [x] equality&#x2F;program.S uses a branching instruction to choose correct path(s)
- [ ] majority&#x2F;program.S uses an LDRB instruction with an offset
- [x] majority&#x2F;program.S uses a branching instruction
- [ ] majority&#x2F;program.S uses AND bitwise logic instruction
- [ ] majority&#x2F;program.S uses an OR bitwide logic instruction
- [ ] majority&#x2F;program.S loads the format string to print output
- [ ] majority&#x2F;program.S loads the true string to print majority outcome
- [ ] majority&#x2F;program.S loads the false string to print no majority outcome
- [ ] majority&#x2F;program.S uses the printf instruction
- [ ] majority&#x2F;program.S uses a comparison instruction
- [x] majority&#x2F;program.S uses a branching instruction to choose correct path(s)

## Digital Circuits

- [ ] majority circuit diagram appears as a PNG (majority.png) in majority directory

## Documentation

- [ ] docs&#x2F;report.md answers all questions

## Percent complete

Based on the checks achieved, this assignment is `23%` complete.
